name: color_models
description: >-
  A set of classes representing the CMYK, HSI, HSL, HSP, HSB, LAB,
  Oklab, RGB, and XYZ color spaces with methods to convert colors
  between each space.
version: 2.0.0
homepage: https://github.com/james-alex/color_models

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  meta: ^1.7.0
  num_utilities: ^1.0.5
  powers: ^1.0.0+2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
